# Generated by Django 4.1.2 on 2022-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_students_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('employee_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('dept', models.CharField(choices=[('SALES', 'SALES'), ('MARKETING', 'MARKETNIG'), ('HR', 'HR'), ('FINANCE', 'FINANCE')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
